name: Terraformer

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - '**.tf'
      - '**.tfvars'
  
  workflow_dispatch:

jobs:
  terraform_plan:

    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' || github.ref_name != 'master'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out tf_plan_out

  terraform_apply:

    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.ref_type == 'branch' || github.ref_name != 'master'
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
