name: Terraform Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform_apply:

    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out tf_plan_file
      
      - name: Terraform Apply
        run: terraform apply tf_plan_file -auto-approve
