name: Terragrunt Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Plan on Pull Request
        run: |
          terragrunt init
          terragrunt plan -out=tfplan
        env:
          TFPATH: dev # Set this to the environment folder

      - name: Comment Plan on Pull Request
        uses: unsplash/comment-on-pr@v1
        with:
          msg: |
            **Terraform Plan:**
            ```
            $(cat tfplan)
            ```

  apply:
    needs: plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Apply on Merge
        run: |
          terragrunt apply -auto-approve
        env:
          TFPATH: dev # Set this to the environment folder

      - name: Manual Approval
        if: success()
        run: |
          echo "Deployment to development successful. Manually approve before deploying to staging."

  deploy-staging:
    needs: apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Apply on Staging
        run: |
          terragrunt apply -auto-approve
        env:
          TFPATH: staging # Set this to the environment folder
