name: Terraform Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:


concurrency:
  group : ${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform_apply:

    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: env
        env: 
          STATUS: "Starting..."

      - name: Notify slack success
        if: success()
        id: 'notify google chat' # IMPORTANT: reference this step ID value in future Slack steps
        uses: 'google-github-actions/sent-google-chat-webhook@v0.0.1'
        with:
          webhook_url: '${{ secrets.WEBHOOK_URL }}'
          channel: random
          status: Starting...
          color: warning

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - id: 'tf_init'
        name: Terraform Init
        run: terraform init
        continue-on-error: true

      - id: 'tf_plan'
        name: Terraform Plan
        run: terraform plan -out tf_plan_file
        if: ${{ !failure() }}
        continue-on-error: true
  
      - name: Google Chat message for approval
        if: success()
        run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "1",
                          "subtitle": "2"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "3"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Title",
                                          "content": "4"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Lables",
                                          "content": "5"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assignees",
                                          "content": "6"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN ISSUE",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "7"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }
          
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 20
        with:
          secret: ${{ github.TOKEN }}
          approvers: DSdatsme
          minimum-approvals: 1

      - id: 'tf_apply'
        name: Terraform Apply
        run: terraform apply tf_plan_file
        if: ${{ !failure() }}

      # - name: Post notify on success
      #   if: success()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     message_id: ${{ steps.slack.outputs.message_id }}
      #     channel: random
      #     status: "SUCCESS :tada:"
      #     color: good

      # - name: Post notify on failure
      #   if: failure()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     message_id: ${{ steps.slack.outputs.message_id }}
      #     channel: random
      #     status: "FAILED :/"
      #     color: danger
      
