name: Terraform Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SLACK_CHANNEL: CTR68RQ80

concurrency:
  group : ${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform_apply:

    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: env
        env: 
          STATUS: "Starting..."
          MSG_COLOR: "dee647"

      - id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          payload-file-path: ./.github/resources/start-deploy.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - id: 'tf_init'
        name: Terraform Init
        run: terraform init
        continue-on-error: true

      - id: 'tf_plan'
        name: Terraform Plan
        run: terraform plan -out tf_plan_file
        if: ${{ !failure() }}
        continue-on-error: true
  
      - uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload-file-path: ./.github/resources/wait-for-approval.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 20
        with:
          secret: ${{ github.TOKEN }}
          approvers: DSdatsme
          minimum-approvals: 1

      - id: 'tf_apply'
        name: Terraform Apply
        run: terraform apply tf_plan_file
        if: ${{ !failure() }}
        continue-on-error: true

      - name: Check for failures
        uses: slackapi/slack-github-action@v1.22.0
        if: steps.tf_init.outcome != 'success' || steps.tf_plan.outcome != 'success' || steps.tf_apply.outcome != 'success' || failure()
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload-file-path: ./.github/resources/slack-notification-payload-failure.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      
      - uses: slackapi/slack-github-action@v1.22.0
        if: success()
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload-file-path: ./.github/resources/slack-notification-payload-success.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
