name: Terraform Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SLACK_CHANNEL: CTR68RQ80

jobs:
  terraform_apply:

    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          payload-file-path: ./.github/resources/slack-notification-payload.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out tf_plan_file
  
      - uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload-file-path: ./.github/resources/slack-notification-payload.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      - name: Terraform Apply
        run: terraform apply tf_plan_file

      - uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload-file-path: ./.github/resources/slack-notification-payload.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
